// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwEGKvubqKMK7wySXyq8G0_Pjmbz8gK84',
    appId: '1:623882857549:web:16612cfb7f3539defe8004',
    messagingSenderId: '623882857549',
    projectId: 'synapse2-bb450',
    authDomain: 'synapse2-bb450.firebaseapp.com',
    storageBucket: 'synapse2-bb450.appspot.com',
    measurementId: 'G-J563VLRLQW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnWwVTrat6aBs0WDn0r9pTke3W_U4cr2E',
    appId: '1:623882857549:android:42ec13185a1d7651fe8004',
    messagingSenderId: '623882857549',
    projectId: 'synapse2-bb450',
    storageBucket: 'synapse2-bb450.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr53NxSqV006nEWm1aSPuDvZyKeZCFl4k',
    appId: '1:623882857549:ios:a34e52625fb296e3fe8004',
    messagingSenderId: '623882857549',
    projectId: 'synapse2-bb450',
    storageBucket: 'synapse2-bb450.appspot.com',
    iosBundleId: 'com.example.expensesTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr53NxSqV006nEWm1aSPuDvZyKeZCFl4k',
    appId: '1:623882857549:ios:a34e52625fb296e3fe8004',
    messagingSenderId: '623882857549',
    projectId: 'synapse2-bb450',
    storageBucket: 'synapse2-bb450.appspot.com',
    iosBundleId: 'com.example.expensesTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwEGKvubqKMK7wySXyq8G0_Pjmbz8gK84',
    appId: '1:623882857549:web:c38709993b2bafd2fe8004',
    messagingSenderId: '623882857549',
    projectId: 'synapse2-bb450',
    authDomain: 'synapse2-bb450.firebaseapp.com',
    storageBucket: 'synapse2-bb450.appspot.com',
    measurementId: 'G-LLGFNL91K7',
  );

}